Repository istio/cri, pull requests merged in 2020-02, with the labels that each got.

#7 Automator: update common-files@master in istio/cri@master
  LICENSE
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/scripts/lint_go.sh
Labels: cla: yes, size/M

#8 Automator: update common-files@master in istio/cri@master
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#9 Add "gen" target
  Makefile.core.mk
Labels: cla: yes, size/XS

#10 Automator: update common-files@master in istio/cri@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#11 Automator: update common-files@master in istio/cri@master
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS
